-- ==========================================================================
-- NJLRII ADMIN PANEL - DATABASE SETUP MIGRATION SCRIPT
-- ISSN: 2582-8665 | Collaborative Manuscript Tracker & Reviews
-- ==========================================================================

-- ==========================================================================
-- PHASE 1: TABLE SCHEMAS CREATION
-- ==========================================================================

-- 1. Create User Profiles Table
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'author' CHECK (role IN ('super_admin', 'editor', 'student_editor', 'reviewer', 'author')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Manuscripts Tracker Table
CREATE TABLE IF NOT EXISTS public.manuscripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    abstract TEXT NOT NULL,
    keywords TEXT[] NOT NULL DEFAULT '{}',
    manuscript_pdf_url TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'under_review', 'revision', 'accepted', 'rejected')),
    assigned_editor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Reviewer Assignments Table
CREATE TABLE IF NOT EXISTS public.reviewer_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manuscript_id BIGINT REFERENCES public.manuscripts(id) ON DELETE CASCADE,
    reviewer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'completed')),
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 4. Create Peer Reviews Table
CREATE TABLE IF NOT EXISTS public.peer_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES public.reviewer_assignments(id) ON DELETE CASCADE UNIQUE,
    score_originality INT NOT NULL CHECK (score_originality >= 1 AND score_originality <= 10),
    score_structure INT NOT NULL CHECK (score_structure >= 1 AND score_structure <= 10),
    score_citation INT NOT NULL CHECK (score_citation >= 1 AND score_citation <= 10),
    comments_for_author TEXT,
    comments_for_editor TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================================================
-- PHASE 2: ROW-LEVEL SECURITY & POLICIES
-- ==========================================================================

-- Enable Row-Level Security
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manuscripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviewer_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peer_reviews ENABLE ROW LEVEL SECURITY;

-- 1. Profiles Policies
CREATE POLICY "Allow public read access to profiles" ON public.user_profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profiles" ON public.user_profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profiles" ON public.user_profiles
    FOR INSERT WITH CHECK (
        auth.uid() = id
        AND (
            role = 'author'
            OR (auth.jwt() -> 'user_metadata' ->> 'role') = role
        )
    );

CREATE POLICY "Allow super_admin to insert profiles" ON public.user_profiles
    FOR INSERT WITH CHECK (
        (auth.jwt() -> 'user_metadata' ->> 'role') = 'super_admin'
        OR EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'super_admin'
        )
    );

CREATE POLICY "Allow super_admin to update profiles" ON public.user_profiles
    FOR UPDATE USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') = 'super_admin'
        OR EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'super_admin'
        )
    );

CREATE POLICY "Allow super_admin to delete profiles" ON public.user_profiles
    FOR DELETE USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') = 'super_admin'
        OR EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'super_admin'
        )
    );

-- 2. Manuscripts Policies
CREATE POLICY "Allow editorial members full write access to manuscripts" ON public.manuscripts
    FOR ALL USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') IN ('super_admin', 'editor', 'student_editor')
        OR EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role IN ('super_admin', 'editor', 'student_editor')
        )
    );

CREATE POLICY "Allow authors to view and modify their own manuscripts" ON public.manuscripts
    FOR SELECT USING (auth.uid() = primary_author_id);

CREATE POLICY "Allow authors to insert their own manuscripts" ON public.manuscripts
    FOR INSERT WITH CHECK (auth.uid() = primary_author_id);

CREATE POLICY "Allow reviewers to view assigned manuscripts" ON public.manuscripts
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.reviewer_assignments
            WHERE reviewer_assignments.manuscript_id = manuscripts.id
            AND reviewer_assignments.reviewer_id = auth.uid()
        )
    );

-- 3. Reviewer Assignments Policies
CREATE POLICY "Allow editorial members full control over reviewer assignments" ON public.reviewer_assignments
    FOR ALL USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') IN ('super_admin', 'editor')
        OR EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role IN ('super_admin', 'editor')
        )
    );

CREATE POLICY "Allow reviewers to read their own assignments" ON public.reviewer_assignments
    FOR SELECT USING (auth.uid() = reviewer_id);

CREATE POLICY "Allow reviewers to update their assignment status" ON public.reviewer_assignments
    FOR UPDATE USING (auth.uid() = reviewer_id);

-- 4. Peer Reviews Policies
CREATE POLICY "Allow editorial members to view all reviews" ON public.peer_reviews
    FOR SELECT USING (
        (auth.jwt() -> 'user_metadata' ->> 'role') IN ('super_admin', 'editor')
        OR EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role IN ('super_admin', 'editor')
        )
    );

CREATE POLICY "Allow reviewers to submit and read their own reviews" ON public.peer_reviews
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.reviewer_assignments
            WHERE reviewer_assignments.id = peer_reviews.assignment_id
            AND reviewer_assignments.reviewer_id = auth.uid()
        )
    );

CREATE POLICY "Allow authors to read author comments of reviews for their manuscripts" ON public.peer_reviews
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.reviewer_assignments
            JOIN public.manuscripts ON manuscripts.id = reviewer_assignments.manuscript_id
            WHERE reviewer_assignments.id = peer_reviews.assignment_id
            AND manuscripts.primary_author_id = auth.uid()
        )
    );

-- ==========================================================================
-- PHASE 3: AUTOMATIC PROFILE CREATION TRIGGER
-- ==========================================================================

-- Trigger Function to create a user profile automatically upon Supabase signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.user_profiles (id, email, full_name, role)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'full_name', ''),
        COALESCE(new.raw_user_meta_data->>'role', 'author')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind Trigger to auth.users Table
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
